'''NAME: OLUSOLA ROTINWA
EMAIL: TONCAMMARADE@GMAIL.COM.
PHONE: +2348102069557
PROJECT UNDER CODE LAGOS.

Create a program that will play the “dogs and cats” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “dog”. For every digit the user guessed correctly in the wrong place is a “cat.” Every time the user makes a guess, tell them how many “dogs” and “cats” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout the game and tell the user at the end.
Say the number generated by the computer is 1658. An example interaction could look like this:

  Welcome to homepet game! 
  Enter a number: 
  >>> 1234
  2 dogs, 2 cats
  >>> 1256
  4 dogs, 0 cats.'''

import random
def compare_numbers(number, guess):
    homepets = [0,0] #dogs followed by cats
    for x in range(len(number)):
        if number[x] == guess[x]:
            homepets[1] += 1
        else:
            homepets[0] += 1
    return homepets

if __name__ == '__main__':  #to play the game
    play = True  
#random of 4 digit number
    number = str(random.randint (0,9999))
    guesses = 0
 #explanation
    print('lets play the game of homepets')
    print('i will generate a number and you have to guess the numbers one digit at a time')
    print('for every number in the wrong place, you get a cat. For every one in the right place you get a dog.')
    print('the game ends when you get 4 cats')
    print('type exit at any prompt to exit')
    while play:
        guess = input('give your guess')
        if guess == 'exit':
            break
        homepetscount = compare_numbers(number, guess)
        guesses += 1
        print('you have' + str(homepetscount[0]) + 'dogs' + str(homepetscount[1]) + 'cats')
        if homepetscount[1] == 4:
            play = False
            print('you win the game after ' + str(guesses) + 'the number was' + str(number))
            break
        else:
            print('you are not right, try again')
